age = input("How old are you?")
print(f'On your next birthday, you will be str' (int'{first_num} + int'{second_num}')
first_numb = input ("{age}")
second_numb = input ("1")
print()
input("How many egg cartons do you have?")
print("You have eggs")
print()
input("How many cookies do you have?")
input("How many people are there?")
print("Each person may have cookies")
